name: Build Test
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: 'Ubuntu 18 + ROS Melodic', rosdistro: 'melodic', container: 'ros:melodic-ros-base-bionic'}
          - {name: 'Ubuntu 20 + ROS Noetic', rosdistro: 'noetic', container: 'ros:noetic-ros-base-focal'}
    container: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install catkin-tools on melodic
      if: ${{ matrix.config.container == 'ros:melodic-ros-base-bionic' }}
      run: |
        apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        apt update && apt install -y python-wstool python-catkin-tools 
        
    - name: Install catkin-tools on Noetic
      if: ${{ matrix.config.container == 'ros:noetic-ros-base-focal' }}
      run: |
        apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        apt update && apt install -y python3-pip
        pip3 install osrf-pycommon
        apt update && apt install -y python3-wstool python3-catkin-tools
    
    - name: Download ccache
      id: ccache
      shell: cmake -P {0}
      run: |
        set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v$ENV{CCACHE_VERSION}/${{ runner.os }}.tar.xz")
        file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)
        
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}"
        
    - name: ccache cache files
      uses: actions/cache@v1.1.0
      with:
      path: .ccache
      key: ${ { matrix.config.name } }-ccache-${ { steps.ccache_cache_timestamp.outputs.timestamp } }
      restore-keys: |
        ${ { matrix.config.name } }-ccache-
        
    - name: Release Build Test
      working-directory: 
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt update
        apt install -y autoconf libtool git
        mkdir -p $HOME/catkin_ws/src;
        cd $HOME/catkin_ws
        catkin init
        catkin config --extend "/opt/ros/${{matrix.config.rosdistro}}"
        catkin config --merge-devel
        catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
        cd $HOME/catkin_ws/src
        ln -s $GITHUB_WORKSPACE
        wstool init . ./config_utilities/config_utilities.rosinstall
        wstool update
        catkin build -j$(nproc) -l$(nproc) config_utilities
      shell: bash
#    - name: Run Unit Tests
#      working-directory:
#      run: |
#        cd $HOME/catkin_ws/src
#        catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_ENABLE_TESTING=True
#        catkin build terrain_planner --no-deps -i --catkin-make-args tests
#        source $HOME/catkin_ws/devel/setup.bash
#        status=0 && for f in $HOME/catkin_ws/devel/lib/*/*-test; do $f || exit 1; done
#      shell: bash

      

